services:
  app:
    build: .
    image: ticket-system:dev
    env_file: .env
    volumes:
      - .:/var/www              # Hot-reload para desenvolvimento
    ports:
      - "8080:8000"
    depends_on:
      - mongo
      - kafka
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - app

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - dev_mongodb_data:/data/db

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_LOG_LEVEL=TRACE
      - KAFKA_HEAP_OPTS=-Xmx1024m -Xms512m
      - KAFKA_BROKER_ID=1
      - KAFKA_CLUSTER_ID=kafka
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

volumes:
  dev_mongodb_data:
